### ISSUE TITLE
Dependency bloating

### ISSUE THREAD

**Issue by gjkreeft** [openimaj/openimaj#117]
I want to use Openimaj for face detection in images. When I built my project it downloaded some 120 Mb of dependencies for the openimaj faces artifact (v 1.3.5). Some of those looked unnecessary or even suspicious (like flickr, azure bing search, axis, http-client). Some other seem to be for video processing and could be omitted for face detection in static images.

Is it possible to create a minimised pom that only includes the dependencies that are needed for simple face detection?

**Comment by jonhare** [comment]
You'll need to exclude the dependencies for the bits you're not using (see https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#Dependency_Exclusions). The command "mvn dependency:tree" will print out a nice diagram of all the dependencies and where they come from to help you select the ones you're not invested in.

**Comment by gjkreeft** [comment]
Hi Jonathon,

Thanks for the quick reply! I will take a look at the dependency graph, but
it can be difficult to decide which ones are important for face detection.
Some are easy (like azure and Flickr), but for others it's impossible to
tell if they will be used at runtime  (like video-processing en netlib).

Although it may not be a very big problem to have unused dependencies, the
Bing and Flickr jars really made me wonder what openimaj is going to do
with my photo's.

Regards,
Gert-Jan

**Comment by jonhare** [comment]
Bing and Flickr are just used for image dataset support (see http://openimaj.org/tutorial/image-datasets.html, although actually the bing dependency has gone from the dev version because the web service API has changed, so I just implemented it internally). Things like http-client are used for loading data from URLs (with additional support for things like redirections that the Java URL class doesn't offer). You can safely remove all the video bits (probably just by excluding video-processing) if you just want simple face detection. Netlib is probably used (mtj almost certainly is which it's a dependency of). You can remove klt-tracker and FaceTracker as you're not working with video. The jai, sanselan and twelvemonkies dependencies are important for loading images as they work-around a number of bugs in java's default ImageIO subsystem. SnuggleTex can be excluded if you're not intending to render latex strings on your images. euclid can be excluded if you're not intending to work with SVG images. You can safely exclude core-experiment too.

**Comment by gjkreeft** [comment]
Thanks a lot, I will remove all the video-related dependencies. I
definitely don't need them, and they are quite big.
The face detection works really well!
