### ISSUE TITLE
BasicMatcher assuming squared euclidean distance?

### ISSUE THREAD

**Issue by marcelolynch** [openimaj/openimaj#158]
The `org.openimaj.feature.local.matcher.BasicMatcher` keypoint matcher for SIFT uses a threshold value `thres` to filter false positives. 

The class documentation states that `thres` is 

> the threshold which the difference the scores of the top two best matches must differ in order to count the first as a good match.

The method which does this, `checkForMatch`, has a comment stating:

> If the closest is less than `threshold` times distance to second closest, then return the closest match. Otherwise, return NULL.

The relevant code is as follows:
```
if (10 * 10 * distsq1 < thresh * thresh * distsq2) {
       return minkey;
}
else
     return null;
```

I'm curious, besides the value 100 (is it due to an interpretation of `thres * thres` as a percentage?), as to why would `thres` be squared in the comparison. It seems to me (and this is just an impression) that the code is assuming that the distances are squared (in particular the distance variables are called `dst**sq**1` and `dst**sq**2`), but `DoubleFVComparison.EUCLIDEAN` returns the actual distance, not the distance squared. 

I understand that this isn't ultimately a big issue because as `threshold` can take any value one can adjust externally with (t -> 100 * sqrt(t)) to get the actual documented behaviour, but it struck me as odd anyway.

Thank you!

**Comment by jonhare** [comment]
The rationale for that code comes from Lowe's original SIFT matching implementation (which used unsigned integers to represent the features, and so the distances were integers - hence why the threshold was represented as a percentage to avoid rounding). The BasicKeypointMatcher class demonstrates this exactly. 

This class clearly has an issue though because it assumes Euclidean distance rather than sum-squared distance as assumed by the code... I'l fix that!

**Comment by marcelolynch** [comment]
Thank you for the swift response! I noticed you kept the squared distance. In this case, shouldnt the multiplication be by 100*100 instead of 10*10 if `thres` is a percentage? As in `(thres/100)^2`
