### ISSUE TITLE
java.lang.ArithmeticException: / by zero in ResizeProcessor.resizeMaxArea(FImage, int)

### ISSUE THREAD

**Issue by bisoldi** [openimaj/openimaj#86]
While attempting to resize photo's of various unknown sizes, I encountered a divide by zero exception.
The relevant portion of the stacktrace is below:

Exception in thread "main" java.lang.ArithmeticException: / by zero
at org.openimaj.image.processing.resize.ResizeProcessor.resizeMaxArea(ResizeProcessor.java:443)

Upon further review, it appears to only occur when the image height is greater than the width.  In such a circumstance, the whRatio float ends up being 0 as it performs integer division on line 441.  That then causes newWidth on line 442 to be 0 which then causes the exception on line 443.

I don't know anything about the algorithm in general, however if you cast the width / height division to float prior to setting the result to whRatio, it no longer produces a 0 value.

Additionally, i'm not sure if this should be a separate issue or not, but I am also resizing images where the width is greater than the height and the resizing skews the aspect ratio.  Is the resizeMaxArea supposed to keep the aspect ratio?

    final int width = 2687;
    final int height = 3356;
    final int area = width * height;
    final int maxArea = 3700000;

    final float whRatio = (float) width / height;
    System.out.println("whRatio: " + whRatio);
        
    final double newWidth = Math.sqrt(maxArea * whRatio);

    System.out.println("New width: " + newWidth);

**Comment by jonhare** [comment]
Ok, this looks rather buggy - as you've noted there is a problem with performing integer rather than floating point division for the whRatio. There was also an issue with the way the newHeight was computed (using the maxArea rather than the whRatio) which potentially caused the aspect ratio to change. This should now be fixed in commit 8e4fd4acaa65a4a1476126d769d758f6f5071da4 (together with unit tests :)).
